added gem bullet and changes in config/envir/development.rb
kasiaekiert/mapsapp pull request #38
Opened 2019-11-24 19:28 UTC by kasiaekiert

2019-11-26 15:35 UTC, womanonrails commented on Gemfile
> +  gem 'bullet'
I agrree with that

2020-01-26 02:55 UTC, kasiaekiert commented
May I do pull request? Or we will do sth here? 

 Includes method??

2020-01-27 15:08 UTC, womanonrails requested changes

2020-01-27 15:08 UTC, womanonrails commented on Gemfile.lock
> +    rubocop-performance (0.0.1)
When you add only `bullet` gem you cannot have in `Gemfile.lock` changes for `rubocop-performance` or this two gems are dependent. Please run one more time `bundle` command on this branch and check.

2020-01-27 15:08 UTC, womanonrails commented on Gemfile
> +
You have here additional line.

2020-01-27 17:15 UTC, womanonrails approved these changes

2020-01-27 17:16 UTC, merged