issue #27 and #23 missing translation in devise and single qnotes in …
kasiaekiert/mapsapp pull request #62
Opened 2019-12-12 10:26 UTC by kasiaekiert

…helpers

2019-12-14 08:56 UTC, womanonrails commented on app/assets/stylesheets/main.scss
> +   margin-top: 0px;
I agree.

2019-12-14 08:56 UTC, womanonrails commented on app/helpers/application_helper.rb
> +        when 'notice' then 'alert alert-info'
When you have `case` then you don't need to do indent for `when`. You can think about it like in `if` and `else` they have the same indent. So the same rule is for `case` and `when`.

2019-12-14 08:56 UTC, womanonrails commented on config/locales/devise.pl.yml
> +      new:
You forgot to add:
```
reset_password_instructions: 'Send me reset password instructions'
        devise:
          sessions:
            users:
              password:
                new: 'Forget the password?'
```
To polish version of translations.

2019-12-17 10:18 UTC, kasiaekiert commented
Ok check it now please

2019-12-17 14:54 UTC, womanonrails requested changes

2019-12-17 14:54 UTC, womanonrails commented on app/assets/stylesheets/main.scss
> +  margin-bottom: 0 !important;
This is not fixed. You still use `!important`

2019-12-17 14:54 UTC, womanonrails commented on app/helpers/application_helper.rb
> +                    end
You have wrong white spaces and `when` and `end` should be in the same intend.

2020-01-19 11:19 UTC, merged