buttons delete me, add me to event
kasiaekiert/mapsapp pull request #64
Opened 2020-01-02 08:52 UTC by kasiaekiert

2020-01-03 10:53 UTC, womanonrails requested changes

2020-01-03 10:53 UTC, womanonrails commented on Gemfile
> +gem 'rubocop-performance', '~> 0.0.1'
Why did you move this gem here?

2020-01-07 18:17 UTC, womanonrails requested changes
You should split this MR into 2 MRs. One for button styling and one for adding this gem (remember to generate `.rubocop.yml` file)

2020-01-16 18:11 UTC, womanonrails requested changes

2020-01-16 18:11 UTC, womanonrails commented on app/helpers/application_helper.rb
> +        when 'notice' then 'alert alert-info'
Here you have the indentation problem.

2020-01-16 18:11 UTC, womanonrails commented on app/models/place.rb
> +    [name, '-', address].join('')
Here you miss space inside the quotes. You should have `' '`

2020-01-16 18:11 UTC, womanonrails commented on config/initializers/devise.rb
> +  # It can be set to an array that will enable params
It should be possible to set in you editor command to remove all not needed spaces. Then this message from hound should disappear.

2020-01-16 18:11 UTC, womanonrails commented on app/helpers/application_helper.rb
> +        when 'notice' then 'alert alert-info'
You can run rubocop locally it should show similar warnings.

2020-01-16 18:11 UTC, womanonrails commented on config/initializers/devise.rb
> +  # For instance, if you set :request_keys to [:subdomain],
Why you change this comment? This are default comments. You don't need to change them.

2020-01-16 18:11 UTC, womanonrails commented on config/initializers/devise.rb
> +  # For instance, if you set :request_keys to [:subdomain],
Could you move back changes in this file?

2020-01-16 18:11 UTC, womanonrails commented on config/initializers/wrap_parameters.rb
> +# Enable parameter wrapping for JSON. You can disable this
Move back change in comment.

2020-01-19 11:50 UTC, kasiaekiert commented on config/initializers/devise.rb
> +  # For instance, if you set :request_keys to [:subdomain],
yes, I can, do it right now. 

rubocop show it as too long

2020-01-19 11:55 UTC, kasiaekiert commented on config/initializers/wrap_parameters.rb
> +# This file contains settings for ActionController::ParamsWrapper which is enabled by default.
Should i worry about it and change? @womanonrails

2020-01-19 12:01 UTC, kasiaekiert commented
Can I do merge pull request? 

I add extension to show whitespaces - will be easier to work with these problems

2020-01-20 15:29 UTC, womanonrails requested changes

2020-01-20 15:29 UTC, womanonrails commented on config/initializers/wrap_parameters.rb
> +# This file contains settings for ActionController::ParamsWrapper which is enabled by default.
You should not change default comments if you don't need to.

2020-01-20 15:29 UTC, womanonrails commented on config/initializers/devise.rb
> +  # find_for_authentication method and considered in your model lookup.
Please do not change comments form external gems if you don't need to. This change no make sense.

2020-02-03 16:11 UTC, womanonrails approved these changes

2020-02-03 16:13 UTC, merged